### ISSUE TITLE
Tuto MineWeb

### ISSUE THREAD

**Issue by WhiteSkyAngel** [MaximeMichaud/mineweb-install#2]
Hello !
certains screens ne s'affichent pas !
Donc impossibilité de savoir de quoi vous parlez pour les débutants...

**Comment by MaximeMichaud** [comment]
Salut !
Vraiment navré, c'est le tutoriel de Dark.
Je vais en faire un nouveau plus complet !

**Comment by AntoineJT** [comment]
@MaximeMichaud Le lien dans le tuto de DarkScientist est vieux, et le script ne fonctionne plus correctement (mineweb.maximemichaud.me est inaccessible, l'installeur phpmyadmin est cassé)

Il faudrait donc changer l'ancien lien par le nouveau `wget https://raw.githubusercontent.com/MaximeMichaud/mineweb-install/master/mineweb-install.sh`

**Comment by MaximeMichaud** [comment]
Changer l'ancien lien ? Je ne comprends pas.
Le lien n'est pas le problème, c'est le script.

Dark, n'a jamais voulu refaire son tutoriel, par paresse.

En effet, le serveur mineweb.[...] n'est plus.
Entre temps, j'ai fait une refonte du script, et je n'ai commit.

Donc, le fait que mineweb.. soit manquant cela empêche l'URL rewrite sur l'installation de MineWeb, mais cela ne faisait ni plus ni moins.

Bref, ce sera résolu ^^
Je me suis un peu désintéressé de MineWeb entre-temps pour beaucoup de raisons, mais la refonte devrait te faire plaisir !

**Comment by MaximeMichaud** [comment]
> @MaximeMichaud Le lien dans le tuto de DarkScientist est vieux, et le script ne fonctionne plus correctement (mineweb.maximemichaud.me est inaccessible)
> 
> Il faudrait donc changer l'ancien lien par le nouveau `wget https://raw.githubusercontent.com/MaximeMichaud/mineweb-install/master/mineweb-install.sh`
> 
> **Edit:** Il semblerait que le problème ne vienne pas du lien mais du script en lui-même...
Fix : https://github.com/MaximeMichaud/mineweb-install/commit/11fc87f46e04d7e64e46f6c1dba1083d84974c72

Et pour l'issue initial @WhiteSkyAngel : dans le futur, il n'y aura plus besoin de documentation. Quoiqu'il en aura probablement une facultatif et très courte.
Le script sera encore plus automatiser.
