### ISSUE TITLE
mysql-server déjà installé

### ISSUE THREAD

**Issue by Liosfr** [MaximeMichaud/mineweb-install#5]
Bonjour,

Le script corrompt les base SQL déjà existantes si mysql est déjà installé.
Dommage pour moi, j'ai perdu toutes mes bases.

**Comment by MaximeMichaud** [comment]
Bonjour,
Cela ne m'est jamais arrivé, et cela ne devrait pas arriver.
De plus, le script devrait être lancé sur une installation vierge.

Pourquoi cela ne devrait pas arriver ? Ce script installera MYSQL 8, donc si tu as MYSQL 5.7, cela ne mettra qu’à jour.

**Comment by Liosfr** [comment]
Je te confirme que cela a bien fait crash le serveur, sans possibilité de le relancer.
Il fallait, pour le relancer supprimer tous les fichiers .idb et donc, les données.
Il serait intéressant de préciser sur la doc ou sur le readme que ce script doit être utilisé sur une machine vierge.

**Comment by MaximeMichaud** [comment]
Je pense plutôt que c'est une mauvaise manipulation de ta part.
Cela utilise le dépôt officiel de MYSQL ainsi que ses outils.
Dans le plus pire des cas, tu aurais plus juste tout sauvegarder, et réinstaller avec la même précédente version et dump les bases de données afin de ne rien perdre, et d'avoir en plus des sauvegardes.

Et là, on est rendu crash serveur ? Crash du service MYSQL plutôt? D'en plus de fournir aucun logs.
Quoiqu'il en soit, tu es le premier en deux ans, qui me fait part de ça.
D'en plus, comme dit précédemment, cela ne devrait pas arrivé. Ton installation devait être déjà cassé.

**Comment by MaximeMichaud** [comment]
Quoiqu'il en soit, tu n'as pas tort, la documentation devrait être refaite et mieux expliquer.
Je n'ai pas trop innové depuis que je ne sois plus du tout sur MineWeb.

Pour le reste, à toi de voir, d'où venait le problème.
DPKG ne casse pas, sans que rien ne soit déjà cassé.

![image](https://user-images.githubusercontent.com/14856114/98452547-319c6280-211e-11eb-8612-c235e67bf75a.png)

**Comment by Liosfr** [comment]
J’ai refais l’installation, juste pour le fun, et ça a fait planté le service mysql sans possibilité de le relancer.
Impossible de faire une sauvegarde avec mysqldump si le serveur ne démarre pas.

Le script écrase beaucoup de choses, il n’est pas adapté pour des serveurs custom ou avec une configuration déjà établie.

Bonne journée, merci d’avoir lu

**Comment by MaximeMichaud** [comment]
Bien sûr, comment dump, si le service est down.
Tjr aucun logs, si tu sais si bien utiliser Linux, n'utilise pas le script s'il te plaît, bonne journée!
